# Generated by Django 3.2 on 2021-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Enter the testimonial quote')),
                ('author', models.CharField(help_text="Enter the author's name", max_length=200)),
                ('job_title', models.CharField(help_text="Enter the author's title/description", max_length=200)),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
