# Generated by Django 3.2 on 2021-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the project name', max_length=200)),
                ('description', models.TextField(help_text='Describe the project')),
                ('url', models.URLField(help_text="Enter the project's website URL")),
                ('github', models.URLField(help_text="Enter the project's GitHub URL")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
