# Generated by Django 3.2 on 2021-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_info', '0002_auto_20210422_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(help_text="Enter the project's GitHub URL", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(help_text="Enter the project's website URL", null=True),
        ),
    ]
