# Generated by Django 3.2 on 2021-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_info', '0004_auto_20210422_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
