# Generated by Django 3.2 on 2021-04-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_info', '0005_project_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('w', 'Website'), ('c', 'Code')], default='w', help_text='Project type', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Enter the website or GitHub URL', null=True),
        ),
    ]
